
favicon:
  small: /images/favicon-16x16-academic.png
  medium: /images/favicon-32x32-academic.png
  apple_touch_icon: /images/apple-touch-icon-academic.png
  safari_pinned_tab: /images/logo.svg

logo: /images/logo-academic.jpeg

icon: /images/icon-spider.png
icon_menu: /images/icon-menu.png

author:
  name: Albert Einstein
  face: /images/author-face.jpeg
  # motto: God does not play dice with the universe
  field: Physics
  institution: KaiserWilhelm Institut f√ºr Physik

cache:
  enable: false

sidebar: 
  display: true

comments:
  enable: true

gitalk:
  enable: true
  js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

  github_id: iLnezoH # GitHub repo owner
  repo: ilnezoh.github.io # Repository name to store issues
  client_id: 62ee341beddb3d239522 # GitHub Application Client ID
  client_secret: cb91b55f4004c08a638688f12c5afabcfaebff35 # GitHub Application Client Secret
  admin_user: iLnezoH # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language:

css: css
js: js

